secrets:
  kakao:
    authorizeUri: https://kauth.kakao.com
    apiUri: https://kapi.kakao.com
    clientId: 23756df6ba3513c3b269a71d468aed45
    clientSecret: LixDgUjVXoEK8w8phzDu1VQ4evoErsbw
    responseType: code
    grantType: authorization_code
  jwt:
    token:
      secret-key: secretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecret
      expire-length: 2147483646

server:
  uri: http://localhost:8080

jpa:
  hibernate:
    ddl-auto: create
  properties:
    hibernate:
      format-sql: true

log4j:
  logger:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

cloud:
  aws:
    s3:
      bucket: market-photos
    region:
      static: ap-northeast-2

slack:
  url: https://hooks.slack.com/services/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